# Generated by Django 3.0.3 on 2020-09-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0009_auto_20200922_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Essay',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
